version: "3.8"

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - server/.env
    ports:
      - "5000:5000"

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        # On Windows/WSL, host.docker.internal resolves to your host machine
        VITE_API_URL: "http://host.docker.internal:5000/api"
    ports:
      - "3000:80"
    depends_on:
      - api
